name: business
description: "A Shopping is part of big project known as eMart. "

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  file_picker: ^8.0.5
  http: ^1.2.1
  readmore: ^3.0.0
  path_provider: ^2.1.2
  flutter_svg: ^2.0.10+1
  flutter_markdown: ^0.7.1
  flutter_rating_bar: ^4.0.1
  smooth_page_indicator: ^1.1.0
  device_info_plus: ^10.1.0
  permission_handler: ^11.3.1
  animated_text_kit: ^4.2.2

  geolocator: ^12.0.0

  #STATE MANAGEMENT
  bloc: ^8.1.4
  provider: ^6.1.2
  flutter_bloc: ^8.1.6
  hydrated_bloc: ^9.1.5

  #FIREBASE SERVICES
  firebase_auth: ^5.0.0

  firebase_messaging: ^15.0.1

  shared:
    path: ../shared

  shared_repositories:
    path: ../shared_repositories

  # Payment Getway
  razorpay_api:
    git:
      url: https://github.com/rahulsharmadev-community/razorpay_api.git
      ref: main

  jars:
    git:
      url: https://github.com/rahulsharmadev-community/jars.git
      path: packages/jars
      ref: main

  copy_with_extension:
    git:
      url: https://github.com/rahulsharmadev-community/copy_with_extension.git
      ref: main
      path: copy_with_extension

  hive_cache:
    git:
      url: https://github.com/rahulsharmadev-community/hive_cache.git
      ref: main

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.1.6
  flutter_lints: ^4.0.0
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  copy_with_extension_gen:
    git:
      url: https://github.com/rahulsharmadev-community/copy_with_extension.git
      ref: main
      path: copy_with_extension_gen

flutter:
  uses-material-design: true
