var productsJson = [
  {
    "result": "pass",
    "reason": null,
    "model": {
      "productId": "ac41444f-8bf6-4e23-b1fe-565f752c3759",
      "sellerId": "ValidSellerID123",
      "title": "Valid Product Title",
      "thumbnail": "https://example.com/thumbnail.jpg",
      "category": [],
      "shotDescription": "The dart test has a catalog of matches to make your assertion",
      "keywords": [],
      "productBrand": null,
      "mrp": 100.0,
      "imageUrls": ["https://example.com/image1.jpg", "https://example.com/image2.jpg"],
      "warrantyPeriod": null,
      "feature": null,
      "unit": null,
      "detailedSpecs": null,
      "productReviews": [],
      "replacement": null,
      "refund": null,
      "afterSalesService": null,
      "status": "available",
      "discount": 10.0,
      "deliveryMetaData": {},
      "createdAt": "2024-03-12T23:53:58.411114",
      "lastUpdateAt": "2024-03-12T23:53:58.411114"
    }
  },
  {
    "result": "fail",
    "reason": "Invalid Seller ID",
    "model": {
      "productId": "b047c156-157a-493b-95d4-1c678f97d01e",
      "sellerId": "ShortID",
      "title": "Invalid Seller ID Test",
      "thumbnail": "https://example.com/thumbnail.jpg",
      "category": [],
      "shotDescription": "Testing invalid seller ID",
      "keywords": [],
      "productBrand": null,
      "mrp": 50.0,
      "imageUrls": ["https://example.com/image1.jpg"],
      "warrantyPeriod": null,
      "feature": null,
      "unit": null,
      "detailedSpecs": null,
      "productReviews": [],
      "replacement": null,
      "refund": null,
      "afterSalesService": null,
      "status": "available",
      "discount": 5.0,
      "deliveryMetaData": {},
      "createdAt": "2024-03-12T23:55:23.123456",
      "lastUpdateAt": "2024-03-12T23:55:23.123456"
    }
  },
  {
    "result": "fail",
    "reason": 'MRP must be greater than zero.',
    "model": {
      "productId": "dbe4760d-01f8-487f-af10-6a23cd9e76c5",
      "sellerId": "ValidSellerID123",
      "title": "Invalid MRP Test",
      "thumbnail": "https://example.com/thumbnail.jpg",
      "category": ["Electronics"],
      "shotDescription": "Testing invalid MRP",
      "keywords": ["gadget", "electronics"],
      "productBrand": "BrandX",
      "mrp": -20.0,
      "imageUrls": ["https://example.com/image1.jpg", "https://example.com/image2.jpg"],
      "warrantyPeriod": null,
      "feature": null,
      "unit": null,
      "detailedSpecs": null,
      "productReviews": ["Great product!", "Not recommended."],
      "replacement": null,
      "refund": null,
      "afterSalesService": null,
      "status": "available",
      "discount": 15.0,
      "deliveryMetaData": {},
      "createdAt": "2024-03-12T23:57:11.987654",
      "lastUpdateAt": "2024-03-12T23:57:11.987654"
    }
  },
  {
    "result": "fail",
    "reason": "Invalid Title Length",
    "model": {
      "productId": "f8f1b82c-5513-4a47-8e91-b688eb7e8733",
      "sellerId": "ValidSellerID123",
      "title": "A",
      "thumbnail": "https://example.com/thumbnail.jpg",
      "category": ["Fashion"],
      "shotDescription": "Testing invalid title length",
      "keywords": ["clothing", "style"],
      "productBrand": "FashionHub",
      "mrp": 75.0,
      "imageUrls": ["https://example.com/image1.jpg", "https://example.com/image2.jpg"],
      "warrantyPeriod": null,
      "feature": null,
      "unit": null,
      "detailedSpecs": null,
      "productReviews": ["Amazing!", "Not worth the price."],
      "replacement": null,
      "refund": null,
      "afterSalesService": null,
      "status": "available",
      "discount": 20.0,
      "deliveryMetaData": {},
      "createdAt": "2024-03-12T23:59:05.543210",
      "lastUpdateAt": "2024-03-12T23:59:05.543210"
    }
  },
  {
    "result": "fail",
    "reason": "Invalid Thumbnail URL",
    "model": {
      "productId": "d2b8819e-16cb-465b-9d87-0faffca387f2",
      "sellerId": "ValidSellerID123",
      "title": "Invalid Thumbnail URL Test",
      "thumbnail": "invalid_url",
      "category": ["Books"],
      "shotDescription": "Testing invalid thumbnail URL",
      "keywords": ["reading", "literature"],
      "productBrand": "BookWorm",
      "mrp": 30.0,
      "imageUrls": ["https://example.com/image1.jpg", "https://example.com/image2.jpg"],
      "warrantyPeriod": null,
      "feature": null,
      "unit": null,
      "detailedSpecs": null,
      "productReviews": ["Must-read!", "Disappointing."],
      "replacement": null,
      "refund": null,
      "afterSalesService": null,
      "status": "available",
      "discount": 5.0,
      "deliveryMetaData": {},
      "createdAt": "2024-03-13T00:01:12.876543",
      "lastUpdateAt": "2024-03-13T00:01:12.876543"
    }
  },
  {
    "result": "fail",
    "reason": "Invalid Discount",
    "model": {
      "productId": "1ac8961b-3a36-4ce5-a1e2-81a4fcb429d4",
      "sellerId": "ValidSellerID123",
      "title": "Invalid Discount Test",
      "thumbnail": "https://example.com/thumbnail.jpg",
      "category": ["Home & Garden"],
      "shotDescription": "Testing invalid discount",
      "keywords": ["decor", "homeware"],
      "productBrand": "HomeStyle",
      "mrp": 50.0,
      "imageUrls": ["https://example.com/image1.jpg", "https://example.com/image2.jpg"],
      "warrantyPeriod": null,
      "feature": null,
      "unit": null,
      "detailedSpecs": null,
      "productReviews": ["Lovely!", "Not recommended for the price."],
      "replacement": null,
      "refund": null,
      "afterSalesService": null,
      "status": "available",
      "discount": 150.0,
      "deliveryMetaData": {},
      "createdAt": "2024-03-13T00:03:29.654321",
      " lastUpdateAt": "2024-03-13T00:03:29.654321"
    }
  },
  {
    "result": "fail",
    "reason": "Invalid Shot Description Length",
    "model": {
      "productId": "a1c8f16a-9e1e-4173-8b5d-41f5454cb7d7",
      "sellerId": "ValidSellerID123",
      "title": "Invalid Shot Description Length Test",
      "thumbnail": "https://example.com/thumbnail.jpg",
      "category": ["Toys & Games"],
      "shotDescription": "Short",
      "keywords": ["fun", "play"],
      "productBrand": "PlayTime",
      "mrp": 20.0,
      "imageUrls": ["https://example.com/image1.jpg", "https://example.com/image2.jpg"],
      "warrantyPeriod": null,
      "feature": null,
      "unit": null,
      "detailedSpecs": null,
      "productReviews": ["Kids love it!", "Not durable."],
      "replacement": null,
      "refund": null,
      "afterSalesService": null,
      "status": "available",
      "discount": 10.0,
      "deliveryMetaData": {},
      "createdAt": "2024-03-13T00:05:47.987654",
      "lastUpdateAt": "2024-03-13T00:05:47.987654"
    }
  },
  {
    "result": "fail",
    "reason": "Invalid Image URL",
    "model": {
      "productId": "5ec3f8d7-2ef8-4f4f-8ba0-5d7aa7a16baf",
      "sellerId": "ValidSellerID123",
      "title": "Invalid Image URL Test",
      "thumbnail": "https://example.com/thumbnail.jpg",
      "category": ["Electronics"],
      "shotDescription": "Testing invalid image URL",
      "keywords": ["tech", "gadgets"],
      "productBrand": "TechGuru",
      "mrp": 90.0,
      "imageUrls": ["invalid_url", "https://example.com/image2.jpg"],
      "warrantyPeriod": null,
      "feature": null,
      "unit": null,
      "detailedSpecs": null,
      "productReviews": ["Impressive!", "Not worth the hype."],
      "replacement": null,
      "refund": null,
      "afterSalesService": null,
      "status": "available",
      "discount": 8.0,
      "deliveryMetaData": {},
      "createdAt": "2024-03-13T00:08:04.321098",
      "lastUpdateAt": "2024-03-13T00:08:04.321098"
    }
  },
  {
    "result": "fail",
    "reason": "Invalid Product Status",
    "model": {
      "productId": "f42a5979-6753-4d17-b990-19a17760a3a5",
      "sellerId": "ValidSellerID123",
      "title": "Invalid Product Status Test",
      "thumbnail": "https://example.com/thumbnail.jpg",
      "category": ["Clothing"],
      "shotDescription": "Testing invalid product status",
      "keywords": ["fashion", "style"],
      "productBrand": "Fashionista",
      "mrp": 60.0,
      "imageUrls": ["https://example.com/image1.jpg", "https://example.com/image2.jpg"],
      "warrantyPeriod": null,
      "feature": null,
      "unit": null,
      "detailedSpecs": null,
      "productReviews": ["Stylish!", "Not recommended for the price."],
      "replacement": null,
      "refund": null,
      "afterSalesService": null,
      "status": "invalid_status",
      "discount": 15.0,
      "deliveryMetaData": {},
      "createdAt": "2024-03-13T00:10:21.654321",
      "lastUpdateAt": "2024-03-13T00:10:21.654321"
    }
  },
  {
    "result": "fail",
    "reason": null,
    "model": {
      "productId": "e13783c7-5c1d-49b3-8d8d-8fb3a3689632",
      "sellerId": "ValidSellerID123",
      "title": "Valid Product Title",
      "thumbnail": "https://example.com/thumbnail.jpg",
      "category": ["Health & Fitness"],
      "shotDescription": "Valid shot description",
      "keywords": ["fitness", "wellness"],
      "productBrand": "FitLife",
      "mrp": 70.0,
      "imageUrls": ["https://example.com/image1.jpg", "https://example.com/image2.jpg"],
      "warrantyPeriod": null,
      "feature": null,
      "unit": null,
      "detailedSpecs": null,
      "productReviews": ["Highly recommended!", "Great quality."],
      "replacement": null,
      "refund": null,
      "afterSalesService": null,
      "status": "available",
      "discount": 12.0,
      "deliveryMetaData": {},
      "createdAt": "2024-03-13T00:12:38.987654",
      "lastUpdateAt": "2024-03-13T00:12:38.987654"
    }
  }
] as List<Map<String, dynamic>>;
