name: shared_repositories
description: A new Flutter package project.
publish_to: "none"
version: 0.0.1
homepage: homepage
documentation: documentation

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.4.1
  http: ^1.2.1
  hive: ^2.2.3
  flutter_bloc: ^8.1.4
  hydrated_bloc: ^9.1.4
  synchronized: ^3.1.0+1

  google_sign_in: ^6.2.1
  firebase_messaging: ^15.0.1
  firebase_storage: ^12.0.1
  firebase_auth: ^5.1.0
  cloud_firestore: ^5.0.1
  firebase_database: ^11.0.1
  firebase_core: ^3.1.0
  json_annotation: ^4.8.1
  
  
  # Payment Getway
  razorpay_api:
    git:
      url: https://github.com/rahulsharmadev-community/razorpay_api.git
      ref: main

  hive_cache:
    git:
      url: https://github.com/rahulsharmadev-community/hive_cache.git
      ref: main
      
  jars:
    git:
      url: https://github.com/rahulsharmadev-community/jars.git
      ref: main
      path: packages/jars

  shared:
    path: ../shared

  copy_with_extension:
    git:
      url: https://github.com/rahulsharmadev-community/copy_with_extension.git
      ref: main
      path: copy_with_extension

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  copy_with_extension_gen:
    git:
      url: https://github.com/rahulsharmadev-community/copy_with_extension.git
      ref: main
      path: copy_with_extension_gen
