name: json_gen
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.2

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  http: ^1.2.1
  html: ^0.15.4
  jars_core:
    git:
      url: https://github.com/rahulsharmadev-community/jars.git
      path: packages/jars_core
      ref: main
      
  shared:
    path: ../../../shared

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
