name: shared
description: "A new Flutter package project."
version: 0.0.1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
    
  uuid: ^4.3.3
  crypto: ^3.0.3
  equatable: ^2.0.5
  json_annotation: ^4.8.1
  firebase_auth: ^5.0.0
  firebase_core: ^3.1.0
  cloud_firestore: ^5.0.1
  firebase_storage: ^12.0.1
  firebase_database: ^11.0.1

  jars:
    git:
      url: https://github.com/rahulsharmadev-community/jars.git
      path: packages/jars
      ref: main

  copy_with_extension:
    git:
      url: https://github.com/rahulsharmadev-community/copy_with_extension.git
      ref: main
      path: copy_with_extension

dev_dependencies:
  test: ^1.24.9
  lints: ^4.0.0
  build_runner: ^2.4.8
  flutter_lints: ^4.0.0
  json_serializable: ^6.7.1
  copy_with_extension_gen:
    git:
      url: https://github.com/rahulsharmadev-community/copy_with_extension.git
      ref: main
      path: copy_with_extension_gen
