name: shopping
description: "A Shopping is part of big project known as eMart. "
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter


  #UI & UX 
  ico: ^0.0.3
  logger: ^2.1.0
  rxdart: ^0.27.7
  readmore: ^3.0.0
  path_provider: ^2.1.2
  device_info_plus: ^9.1.2
  flutter_svg: ^2.0.10+1
  flutter_markdown: ^0.6.23
  flutter_rating_bar: ^4.0.1
  smooth_page_indicator: ^1.1.0
  flutter_local_notifications: ^17.0.0


  #OTHER SERVICES
  http: ^1.2.1
  cached_network_image: ^3.3.1
  connectivity_plus: ^6.0.2


  #ROUTES MANAGEMENT
  go_router: ^13.2.1


  #STATE MANAGEMENT
  bloc: ^8.1.4
  equatable: ^2.0.5
  flutter_bloc: ^8.1.5
  hydrated_bloc: ^9.1.5 


  #FIREBASE SERVICES
  firebase_auth: ^4.17.9 
  firebase_ui_auth: ^1.13.1
  firebase_messaging: ^14.7.20
  firebase_ui_oauth_google: ^1.3.1

  shared:
    path: ../shared

  repositories:
    path: repositories
  meta: ^1.11.0

  jars:
    git:
      url: https://github.com/rahulsharmadev-community/jars.git
      ref: main
      path: packages/jars

dev_dependencies:
  bloc_test: ^9.1.6
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/icons/

fonts:
  - family: SocialIcons
    fonts:
      - asset: packages/firebase_ui_auth/fonts/SocialIcons.ttf
 