name: repositories
description: A new Flutter package project.
publish_to: "none"
version: 0.0.1
homepage: homepage
documentation: documentation

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
    
  dio: ^5.4.1
  http: ^1.2.1
  logger: ^2.1.0
  google_sign_in: ^6.2.1
  
  firebase_messaging: ^14.7.20
  firebase_storage: ^11.6.10
  firebase_auth: ^4.17.9
  cloud_firestore: ^4.15.9
  firebase_database: ^10.4.10
  firebase_core: ^2.27.1

  shared:
    path: ../../../shared

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
